@startuml component
package "PasswordResetSettings" {
	class PasswordResetSettings {
		AutoGenerate : Boolean
		DefaultPassword : String
		DisableNotifications : Boolean
		GeneratedDigitCharsCount : Int32
		GeneratedLength : Int32
		GeneratedLowerCaseCharsCount : Int32
		GeneratedSymbolCharsCount : Int32
		GeneratedUpperCaseCharsCount : Int32
		Identifier : String
		Mode : Int64
		MustChange : Boolean
		NotificationCC : String
		StrengthCheck : String
		--
		BeneficiaryEmailBinding : Binding
		BeneficiaryFullNameBinding : Binding
		NotifiedEmailBinding : Binding
		NotifiedFullNameBinding : Binding
		PasswordResetSetting : ResourceTypeMapping[]
	}
}
package "Binding" {
	class Binding {
	}
}
package "ResourceTypeMapping" {
	class ResourceTypeMapping {
	}
}
PasswordResetSettings "0..*" --  "0..1"Binding
PasswordResetSettings "0..*" --  "0..1"Binding
PasswordResetSettings "0..*" --  "0..1"Binding
PasswordResetSettings "0..*" --  "0..1"Binding
PasswordResetSettings "0..1" --  "0..*"ResourceTypeMapping
hide empty members
@enduml
