name: Fix site
description: Report an issue with the documentation site functionality.
title: "Fix: "
labels: ["fix", "site", "docusaurus"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a site issue!
        Please provide as much information as possible to help us understand and reproduce the issue.
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue type
      description: Select the issue type that most closely applies (you can select multiple).
      multiple: true
      options:
        - The site is not working as expected.
        - Navigation or menu issues
        - Search functionality issues
        - Page layout or display issues
        - Links aren't working correctly, though the URLs should be correct.
        - Images aren't loading, or they're displaying incorrectly.
        - Performance issues (slow loading, freezing, etc.)
        - Mobile responsiveness issues
    validations:
      required: false
  - type: textarea
    id: issue-description
    attributes:
      label: Issue
      description: |
        Please provide a detailed description of the issue.
        Please include the relevant URLs where you encountered the issue.
        Include any error messages, screenshots, or recordings that might help us understand the problem.
        The more information you provide, the faster we can address your request.
      placeholder: |
        Example: "The search function returns no results when searching for 'Auditor installation'"
        URL: https://docs.netwrix.com/...
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      description: |
        Please provide the steps we need to take to reproduce the issue.
        If you're unable to reproduce the issue, please describe the situation you encountered the issue in with as much detail as possible.
        Include any useful screenshots or recordings.
      placeholder: |
        Example: "1. Go to '...' 2. Click on '....' 3. Scroll down to '....' 4. See error"
    validations:
      required: false
  - type: textarea
    id: solution-description
    attributes:
      label: Solution
      description: |
        If you already know what needs to be done, please tell us what you think needs to be done to fix the issue.
        The documentation site is generated by Docusaurus, so the [Docusaurus documentation](https://docusaurus.io/docs) will be helpful for any solutions you're considering.
        Please provide any useful resources like existing documentation, blog posts, diagrams, videos, or other materials that might help us understand the solution.
      placeholder: |
        Example: "The search index needs to be rebuilt to include newer documentation."
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: Browsers
      description: What browser are you using?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Brave
        - Opera
        - Other
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: What operating system are you using?
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux
        - Other
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Contact details
      description: Please provide us with your contact details so we can follow up with you if we need more information.
      placeholder: ex. email@example.com
    validations:
      required: false