@startuml component
package "ResourceLink" {
	class ResourceLink {
		--
		R1 : Resource
		R2 : Resource
		Type : EntityAssociation
	}
}
package "Resource" {
	class Resource {
	}
}
package "EntityAssociation" {
	class EntityAssociation {
	}
}
ResourceLink "0..*" --  "1"Resource
ResourceLink "0..*" --  "1"Resource
ResourceLink "0..*" --  "1"EntityAssociation
hide empty members
@enduml
